# Generated by Django 4.2 on 2023-05-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='catalog',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-fiction')], default='non-fiction', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('story', 'Story'), ('poem', 'Poem'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
